/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KaikkiRouteImport } from './routes/kaikki'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaikkiNameRouteImport } from './routes/kaikki.$name'

const KaikkiRoute = KaikkiRouteImport.update({
  id: '/kaikki',
  path: '/kaikki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaikkiNameRoute = KaikkiNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => KaikkiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRouteWithChildren
  '/kaikki/$name': typeof KaikkiNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRouteWithChildren
  '/kaikki/$name': typeof KaikkiNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRouteWithChildren
  '/kaikki/$name': typeof KaikkiNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kaikki' | '/kaikki/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kaikki' | '/kaikki/$name'
  id: '__root__' | '/' | '/kaikki' | '/kaikki/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KaikkiRoute: typeof KaikkiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kaikki': {
      id: '/kaikki'
      path: '/kaikki'
      fullPath: '/kaikki'
      preLoaderRoute: typeof KaikkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaikki/$name': {
      id: '/kaikki/$name'
      path: '/$name'
      fullPath: '/kaikki/$name'
      preLoaderRoute: typeof KaikkiNameRouteImport
      parentRoute: typeof KaikkiRoute
    }
  }
}

interface KaikkiRouteChildren {
  KaikkiNameRoute: typeof KaikkiNameRoute
}

const KaikkiRouteChildren: KaikkiRouteChildren = {
  KaikkiNameRoute: KaikkiNameRoute,
}

const KaikkiRouteWithChildren =
  KaikkiRoute._addFileChildren(KaikkiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KaikkiRoute: KaikkiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
