/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KaikkiRouteImport } from './routes/kaikki'
import { Route as IndexRouteImport } from './routes/index'

const KaikkiRoute = KaikkiRouteImport.update({
  id: '/kaikki',
  path: '/kaikki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kaikki': typeof KaikkiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kaikki'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kaikki'
  id: '__root__' | '/' | '/kaikki'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KaikkiRoute: typeof KaikkiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kaikki': {
      id: '/kaikki'
      path: '/kaikki'
      fullPath: '/kaikki'
      preLoaderRoute: typeof KaikkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KaikkiRoute: KaikkiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
